name: CaptainPortal
main: me.captain.portal.CaptainPortal
author: captainawesome7
version: 1.1
api-version: 1.12
softdepend: [CaptainLock,CaptainWarp]
commands:
  portal:
    Description: Do portal stuff
    Usage: /portal <stuff>